### ISSUE TITLE
Bug example gridgoboot

### ISSUE THREAD

**Issue by hoanguyenkh** [gridgo/gridgo-examples#4]
When i run example gridgoboot got warning:

> WARN  DataAccessInjector:55 - Class io.gridgo.boot.data.support.impl.AbstractDataAccessHandler is not annotated with @DataAccessSchema

And error:

> ERROR KafkaConsumer:224 - Exception caught on consumer thread
java.lang.NullPointerException: null
	at io.gridgo.connector.kafka.KafkaConsumer$KafkaFetchRecords.deserializeWithFormat(KafkaConsumer.java:143) ~[gridgo-kafka-0.6.0-20190412.114351-8.jar:?]
	at io.gridgo.connector.kafka.KafkaConsumer$KafkaFetchRecords.buildMessage(KafkaConsumer.java:137) ~[gridgo-kafka-0.6.0-20190412.114351-8.jar:?]
	at io.gridgo.connector.kafka.KafkaConsumer$KafkaFetchRecords.processSingleRecord(KafkaConsumer.java:295) ~[gridgo-kafka-0.6.0-20190412.114351-8.jar:?]
	at io.gridgo.connector.kafka.KafkaConsumer$KafkaFetchRecords.fetchAndProcess(KafkaConsumer.java:258) ~[gridgo-kafka-0.6.0-20190412.114351-8.jar:?]
	at io.gridgo.connector.kafka.KafkaConsumer$KafkaFetchRecords.doRun(KafkaConsumer.java:212) [gridgo-kafka-0.6.0-20190412.114351-8.jar:?]
	at io.gridgo.connector.kafka.KafkaConsumer$KafkaFetchRecords.run(KafkaConsumer.java:340) [gridgo-kafka-0.6.0-20190412.114351-8.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

I setup SDK 11.0.2,
How fix it?
Thanks!

**Comment by huanpc** [comment]
Thank you for your feedback!
Your issue will be fixed in this PR [#5](https://github.com/gridgo/gridgo-examples/pull/5)
